services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partilha_dev
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - partilha

  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    command: npm run start:dev
    volumes:
      - ../..:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - ../../.env
    depends_on:
      - db
    networks:
      - partilha

volumes:
  db_data:

networks:
  partilha:
    driver: bridge
